### PR TITLE
Handle verify_hostname ssl option

### PR DESCRIPTION
**Pull request by kazarin**
Hi,
This is support for https://github.com/lostisland/faraday/pull/1428 option. Also I am thinking about adding specs, but don't know yet what can be added

### CODE REVIEW

**Comment by iMacTia** [comment]
Thank you @kazarin, you can add a test that checks if `http` was configured correctly in [this file](https://github.com/lostisland/faraday-net_http/blob/main/spec/faraday/adapter/net_http_spec.rb). We test other configuration fields similarly, so you should be able to take inspiration from them.

As for the failing tests in Ruby 3.0+, it seems like something changed in the way Ruby checks for structs, and is raising an error when the field you're looking for doesn't belong to the struct. This means this change will break in versions of Faraday that do not support the new SSL option.

Ideally, we should make the code work with older versions of Faraday prior to the introduction of the new field

**Comment by kazarin** [comment]
Thanks for detailed explanation @iMacTia!
Added specs and support for older versions of faraday

**Review by iMacTia — APPROVED** [review]
Thank you @kazarin, LGTM 👍!
Just a few minor Rubocop issues that need fixing before we can merge this

**Comment by kazarin** [comment]
Sorry for little mess. 
Finally fixed rubocop warnings and modified specs for a little

**Comment by iMacTia** [comment]
No worries at all, thank you for fighting with the specs till the end 😄!
It makes sense to test only the scenario for Faraday 2.3 as you did in the last commit 👍

**Comment by bnhassin** [comment]
[Alright that opened on this direct link]( https://github.com/lostisland/faraday-net_http/pull/23)

**Pull request merged**
