### PR TITLE
net_http adapter: Backport the code of #38 to version 1.0.1

### PR DESCRIPTION
**Pull request by ma2gedev**
This PR is the backport of #38 to version v1.0.1 . 

Could you create a branch for version 1.0.1 (something like 1.x)? I've temporarily set the target branch to main, but I will change the target branch of the PR to the new one afterwards.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@ma2gedev I will make a 1-0-stable branch, where https://github.com/lostisland/faraday-net_http/tree/v1.0.1 is.

**Comment by olleolleolle** [comment]
@ma2gedev Now, there exists a branch.

**Comment by ma2gedev** [comment]
@olleolleolle Thank you so much! ❤️

**Comment by olleolleolle** [comment]
@ma2gedev In order to get to a release of 1.0.2, there was a little oil change needed. But now, I think any subsequent 1-0-stable release can be done using our automation.

https://rubygems.org/gems/faraday-net_http/versions/1.0.2 now exists.

**Comment by ma2gedev** [comment]
@olleolleolle Thank you for your work about both of 1.0.2 and 3.1.1. ❤️

**Comment by olleolleolle** [comment]
No, thank _you_ for suggesting it!

**Comment by dpsi** [comment]
thank you everyone involved here, as someone who is stuck on faraday v1 still, it is much appreciated!

**Pull request merged**
