### PR TITLE
CI: Use Ruby 3.3 for linting

### PR DESCRIPTION
**Pull request by olleolleolle**
RuboCop is set to use 2.6 syntax rules in any case.

---

Turned out to need a newer RuboCop, and newer plugins, and after that, it was ready to be used.

### CODE REVIEW

**Comment by iMacTia** [comment]
Next release will drop Ruby 2.6 and 2.7 anyway, so feel free to remove them in this PR if it helps getting CI green 👍

**Review by iMacTia — APPROVED** [review]

**Comment by olleolleolle** [comment]
The real reason was "used a bundled Bundler which had some older issues", but now, we got rid of the 2.6, 2.7 from the CI matrix. Should we bump the gemspec min required Ruby version, too, @iMacTia ?

**Comment by iMacTia** [comment]
Yes we'll need to bump it in the gem spec and also in the rubocop.yml file.
Also, I wanted to check if we need to put a version restriction on `net-http`.
All these can go into a separate PR though, happy to get this merged in the meantime to unblock CI

**Comment by olleolleolle** [comment]
@iMacTia I will refrain from checking for version restriction on the net-http gem, but the rest of the things are here, and I will merge.

**Pull request merged**
